"use strict";
var hospital;
(function (hospital) {
    var p = new hospital.Paciente();
    p.setnome("Marcos");
    p.setcpf("111.111.111-11");
    p.setcodPaciente(1);
    var p1 = new hospital.Paciente();
    p1.setnome("Julia");
    p1.setcpf("222.222.222-22");
    p1.setcodPaciente(2);
    var p2 = new hospital.Paciente();
    p2.setnome("Cesar");
    p2.setcpf("333.333.333-33");
    p2.setcodPaciente(3);
    var e = new hospital.Enfermeiro();
    e.setnome("Jubscrelza");
    e.setcpf("123.123.123-12");
    e.setcodFuncionario(1);
    e.setcoren(12);
    var e1 = new hospital.Enfermeiro();
    e1.setnome("Fernanda");
    e1.setcpf("345.345.345-34");
    e1.setcodFuncionario(2);
    e1.setcoren(12);
    var e2 = new hospital.Enfermeiro();
    e2.setnome("Gabriela");
    e2.setcpf(".567.567.567-56");
    e2.setcodFuncionario(3);
    e2.setcoren(13);
    var m = new pessoa.Medico();
    m.setnome("Catapinbas");
    m.setespecialidade("Anestesista");
    m.setcrm(123);
    m.setcpf("001.123.001-11");
    m.setcodFuncionario(21);
    var m1 = new pessoa.Medico();
    m1.setnome("Tobias");
    m1.setespecialidade("Cirurgião");
    m1.setcrm(456);
    m1.setcpf("123.001.001-12");
    m1.setcodFuncionario(22);
    var m2 = new pessoa.Medico();
    m2.setnome("Mariscrelza");
    m2.setespecialidade("Pediatra");
    m2.setcrm(789);
    m2.setcpf("001.001.123-13");
    m2.setcodFuncionario(23);
    var h = new hospital.Hospital();
    h.setNomeHospital("Instituiçao Hobscrelzo Socorre");
    h.addEnfermeiros(e);
    h.addEnfermeiros(e1);
    h.addEnfermeiros(e2);
    h.addMedicos(m);
    h.addMedicos(m1);
    h.addMedicos(m2);
    h.addPacientes(p);
    h.addPacientes(p1);
    h.addPacientes(p2);
    document.getElementById("hospital").textContent = h.getNomeHospital();
    var tbMedico = document.getElementById("tbMedico");
    h.getmedicos().forEach(function (h) {
        var nome = h.getnome();
        var cpf = h.getcpf();
        var crm = h.getcrm();
        var especialidade = h.getespecialidade();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + crm + "</td><td>" + especialidade + "</td></tr>";
        tbMedico.innerHTML += html;
    });
    var tbEnfermeiras = document.getElementById("tbEnfermeiras");
    h.getEnfermeiros().forEach(function (h) {
        var nome = h.getnome();
        var cpf = h.getcpf();
        var corem = h.getcoren();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + corem + "</td></tr>";
        tbEnfermeiras.innerHTML += html;
    });
    var tbPacientes = document.getElementById("tbPacientes");
    h.getpacientes().forEach(function (h) {
        var nome = h.getnome();
        var cpf = h.getcpf();
        var cod = h.getcodPaciente();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + cod + "</td></tr>";
        tbPacientes.innerHTML += html;
    });
})(hospital || (hospital = {}));

